# 数据库配置
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_DATABASE = 'STPMDatas'
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'root'
# 邮件配置
MAIL_HOST = "smtp.163.com"
MAIL_PORT = 465
MAIL_USER = "wangjk_ing@163.com"
MAIL_PASSWORD = "YUAGEVVZMYUSSBCJ"